return {
    {"filloax", "lead coder", "video", tooltip = {"could be", "worse,", "could be", "raining"}},
    {"gummy", "lead artist", tooltip = {"come visit", "prank's", "funny shack"}},
    {"ashkal", "founder", "artist", tooltip = {"haven't shit", "myself", "in a while."}},
    {"sentinel", "founder", "coder", tooltip = {"i've been stuck", "in this tomb", "for months"}},

    {"baicherra", "artist", tooltip = {"i eat souls!"}},
    {"blorenge", "artist", "rooms", tooltip = {"i am", "blorenge", "rhymes"}},
    {"jontherealjon", "artist", tooltip = {"video games", "are evil"}},
    {"notyoursagittarius", "artist", tooltip = {"repentance?", "i wanted", "revengeance"}},
    {"origami", "artist", tooltip = {"we don't talk", "about alpha"}},
    {"peas", "artist", tooltip = {"item that", " makes ice", "floes when"}},
    {"poyo", "artist", tooltip = {"hi :)"}},
    {"quartz", "artist"},
    {"snakeblock", "artist", tooltip = {"hi i am", "snake block"}},
    {"thx", "artist", tooltip = {"i forgot", "i worked on", "this"}},
    {"titaniumgrunt7", "artist", "rooms", "vermin", tooltip = {"you are the", "chosen one,", "i am the", "chosen two"}},

    {"budjmt", "coder", tooltip = {"nobody", "expects", "the spanish", "inkquisition"}},
    {"deadinfinity", "coder", tooltip = {"please fight", "all of our", "lovely", "bosses"}},
    {"ferrium", "coder", tooltip = {"jd was here"}},
    {"gavitro", "coder"},
    {"guwahavel", "coder"},
    {"hippocrunchy", "coder", "rooms", tooltip = {"i paid them 5", "bones to put", "my name", "in here"}},
    {"piber", "coder", tooltip = {"egg"}},

    {"wertandrew", "music", "sfx", tooltip = {"music has", "appeared in", "the basement"}},
    {"happyhead", "sfx", "3d", tooltip = {"a"}},
    {"shapatsmith", "announcer"},
    {"grynn", "wiki", "testing", tooltip = {"sarah", "best girl"}},

    {"al", "rooms"},
    {"anonymouskoala", "design", "rooms", tooltip = {"i'm koala", "goin to the", "septic"}},
    {"boogs", "testing"},
    {"bullet", "testing", tooltip = {"send me", "edith art"}},
    {"bustin", "testing", tooltip = {"makes me", "feel good"}},
    {"creeps", "testing", "rooms", tooltip = {"coming soon", "to a closet", "near you!"}},
    {"electoon", "testing", tooltip = {"ringer rin", "ry rutt"}},
    {"jerb", "testing", tooltip = {"emffles", "took all the", "good quotes"}},
    {"kindaloveable", "testing", tooltip = ":eyes:"},
    {"melon", "design", "coder", "rooms", tooltip = {"please enjoy", "my stone", "wall creeps"}},
    {"minichibis", "testing", "artist", tooltip = {"this quote", "made by", "fiend gang"}},
    {"pasta", "testing", "rooms", tooltip = {"new enemies", "and more!?"}},
    {"pixelo", "testing", "rooms", tooltip = {"caught a fever"}},
    {"pkpseudo", "testing", "rooms"},
	{"robby shenanigans", "testing", tooltip = {"if you guys", "don't", "appreciate", "dramamine", "i'm gonna be", "pissed"}},
    {"sin", "testing", "rooms"},
	{"sunil b", "testing", "rooms", tooltip = {"now where", "could my", "pipe be?", "", "garfield!"}},

    
    "",
    "special thanks to",
    {"lung", "menu sprites", tooltip = {"gonna drink", "water", "(directly from", "the fridge)"}},
    {"apollyon woman", "menu palettes", tooltip = {"(clap)", "dododododo", "(clap)"}},
    {"akio", "veggie sprites", tooltip = {"buy communist", "manifesto"}},
    {"taigatreant", "custom gameover", tooltip = {"i rate", "this mod", "5 stars"}},
    {"sbody2", "spongebomb synergies gfx", tooltip = {"our daddy", "taught us", "not to be", "ashamed", "of our bombs."}},
    {"kilburn", "repentance", "you know", "it's pretty cool", tooltip = {"i'm ", "gay"}},
    "the isaac community",
}