return {
    MOMS_KNIFE = 0,
    BONE_CLUB = 1,
    BONE_SCYTHE = 2,
    NOTCHED_AXE = 9,
    DONKEY_JAWBONE = 3,
    BAG_OF_CRAFTING = 4,
    SUMPTORIUM = 5,
    SPIRIT_SWORD = 10,
    TECH_SWORD = 11,
}