return {
    CHILL = "Chill",
    CHILL_CHALLENGE = "ChillChallenge",
    CHILL_FREEZER_BURN = "ChillFreezerBurn",
    ICE_BOSS = "IceBoss",
    DANTE_MEGA_SATAN = "DanteSatanBig",
    FLAMING_TOMBS = "FlamingTombs",
    TRAP = "Trap",
    TRAP_BOSS = "TrapBoss",
    TRAP_BOSS_MAXWELL = "TrapBossMaxwell",
    TRAP_BOSS_SARCOPHAGUTS = "TrapBossSarcophaguts",
    TRAP_CHALLENGE = "TrapChallenge",
    TRAP_SECRET = "TrapSecret",
    BOSS_SANDY = "BossSandy",
    MIRROR = "Mirror",
    HUB2D = "RevelationsHub",
    VANITY = "VanityShop",
    CASINO = "CasinoVanity",
}